const List<Map<String, String>> tracklistSongsData = [
  {
    'title': 'Rap or Go to the League',
    'artist': '2 Chainz',
    'duration': '3:54',
    'cover': 'tracklist_image_1.jpg',
  },
  {
    'title': 'Real Hasta La Muerte 2',
    'artist': 'Anuel AA',
    'duration': '4:07',
    'cover': 'tracklist_image_2.jpg',
  },
  {
    'title': 'thank u, next',
    'artist': 'Ariana Grande',
    'duration': '3:29',
    'cover': 'tracklist_image_3.jpg',
  },
  {
    'title': 'when the party’s over',
    'artist': 'Billie Eilish',
    'duration': '4:25',
    'cover': 'tracklist_image_4.jpg',
  },
  {
    'title': 'Invasion of Privacy',
    'artist': 'Cardi B',
    'duration': '2:43',
    'cover': 'tracklist_image_5.jpg',
  },
  {
    'title': 'No Problem',
    'artist': 'Chance the Rapper',
    'duration': '3:54',
    'cover': 'tracklist_image_6.jpg',
  },
  {
    'title': '2099',
    'artist': 'Charli XCX',
    'duration': '4:07',
    'cover': 'tracklist_image_7.jpg',
  },
  {
    'title': 'This Is America',
    'artist': 'Childish Gambino',
    'duration': '3:29',
    'cover': 'tracklist_image_8.jpg',
  },
  {
    'title': 'Revenge of The Dreamers III',
    'artist': 'Dreamville',
    'duration': '4:25',
    'cover': 'tracklist_image_9.jpg',
  },
  {
    'title': 'New Rules',
    'artist': 'Dua Lipa',
    'duration': '2:43',
    'cover': 'tracklist_image_10.jpg',
  },
  {
    'title': 'Thinking Bout You',
    'artist': 'Frank Ocean',
    'duration': '3:54',
    'cover': 'tracklist_image_11.jpg',
  },
  {
    'title': 'Oblivion',
    'artist': 'Grimes',
    'duration': '3:54',
    'cover': 'tracklist_image_12.jpg',
  },
  {
    'title': 'The Fall Off',
    'artist': 'J. Cole',
    'duration': '4:07',
    'cover': 'tracklist_image_13.jpg',
  },
  {
    'title': 'Yandhi',
    'artist': 'Kanye West',
    'duration': '3:29',
    'cover': 'tracklist_image_14.jpg',
  },
  {
    'title': 'Nights Like This,',
    'artist': 'Kehlani',
    'duration': '4:25',
    'cover': 'tracklist_image_15.jpg',
  },
  {
    'title': 'Norman Fucking Rockwell',
    'artist': 'Lana Del Rey',
    'duration': '2:43',
    'cover': 'tracklist_image_16.jpg',
  },
  {
    'title': 'Eternal Atake',
    'artist': 'Lil Uzi Vert',
    'duration': '3:54',
    'cover': 'tracklist_image_17.jpg',
  },
  {
    'title': 'Red Room',
    'artist': 'Offset',
    'duration': '3:54',
    'cover': 'tracklist_image_18.jpg',
  },
  {
    'title': 'Umbrella',
    'artist': 'Rihanna',
    'duration': '4:07',
    'cover': 'tracklist_image_19.jpg',
  },
  {
    'title': 'Run the Jewels 4',
    'artist': 'Run the Jewels',
    'duration': '3:29',
    'cover': 'tracklist_image_20.jpg',
  },
  {
    'title': 'Blank Face',
    'artist': 'ScHoolboy Q',
    'duration': '4:25',
    'cover': 'tracklist_image_21.jpg',
  },
  {
    'title': 'A Seat at the Table',
    'artist': 'Solange',
    'duration': '2:43',
    'cover': 'tracklist_image_22.jpg',
  },
  {
    'title': 'A',
    'artist': 'SZA',
    'duration': '3:54',
    'cover': 'tracklist_image_23.jpg',
  },
  {
    'title': 'Currents',
    'artist': 'Tame Impala',
    'duration': '3:54',
    'cover': 'tracklist_image_24.jpg',
  },
  {
    'title': 'Chapter VI',
    'artist': 'The Weeknd',
    'duration': '4:07',
    'cover': 'tracklist_image_25.jpg',
  },
];

const List<Map<String, String>> playableSongsData = [
  {
    'title': 'Standing on the edge',
    'artist': 'Lav',
    'file': 'Lav_-_standing_on_the_edge.mp3',
    'cover': 'playlist_image_1.jpg',
  },
  {
    'title': 'Hachiko (The Faithtful Dog)',
    'artist': 'The Kyoto',
    'file': 'The_Kyoto_Connection_-_09_-_Hachiko_The_Faithtful_Dog.mp3',
    'cover': 'playlist_image_2.jpg',
  },
  {
    'title': 'I Used to Think',
    'artist': 'Loveshadow',
    'file': 'Loveshadow_-_I_Used_to_Think.mp3',
    'cover': 'playlist_image_3.jpg',
  },
  {
    'title': 'Standing on the edge',
    'artist': 'Lav',
    'file': 'Lav_-_standing_on_the_edge.mp3',
    'cover': 'playlist_image_4.jpg',
  },
  {
    'title': 'Hachiko (The Faithtful Dog)',
    'artist': 'The Kyoto',
    'file': 'The_Kyoto_Connection_-_09_-_Hachiko_The_Faithtful_Dog.mp3',
    'cover': 'playlist_image_5.jpg',
  },
  {
    'title': 'I Used to Think',
    'artist': 'Loveshadow',
    'file': 'Loveshadow_-_I_Used_to_Think.mp3',
    'cover': 'playlist_image_6.jpg',
  },
];

const List<String> letters = [
  "#",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];
